version: '2'
services:
  apiserver:
    build: apiserver
    command: python server.py
  nginx:
    image: nginx
    ports:
      - 8044:8044
    volumes:
      - \youarewelcome-master\nginx.conf:/etc/nginx/nginx.conf:ro
      - \youarewelcome-master\web:/web/:ro
#  node:
#    image: node
#    ports:
#      - 8045:8045
#    volumes:
#      - \youarewelcome-master\web:/web/:ro
